title: "Daiki Tomojiri"
description: "Personal academic website of Daiki Tomojiri"
theme: null
markdown: kramdown

plugins:
  - jekyll-sitemap

url: "https://tjdk1992.github.io"
baseurl: ""

permalink: pretty