title: "Daiki Tomojiri-Kadotani"
description: "Official academic website of Daiki Tomojiri-Kadotani, aquatic ecologist based in Kyoto, Japan."
theme: null
markdown: kramdown

url: "https://tjdk1992.github.io"
baseurl: ""

permalink: pretty